inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 2.2
  Include:
    - Rakefile
    - config.ru
    - lib/**/*.rake
# The cop is meant to enforce conventions regarding variables containing numbers
# However in 0.43.0 it is bugged. Both changed on master and disabled by default
# The exclusions don't even get added to the rubocop_todo properly!
Naming/VariableNumber:
  Enabled: false
Rails:
  Enabled: true
