language: ruby
dist: xenial
bundler_args: "--without deployment"
sudo: required
services:
- xvfb
addons:
  apt:
    packages:
    - haveged
    - google-chrome-stable
    - chromium-chromedriver
cache:
  bundler: true
env:
  global:
  - TZ=Europe/London
  - PATH=$PATH:/usr/lib/chromium-browser/
script:
- bundle exec rubocop
- xvfb-run -a bundle exec rake
before_deploy: "./compile-build"
deploy:
  provider: releases
  file: release.tar.gz
  file_glob: true
  skip_cleanup: true
  on:
    tags: true
    repo: sanger/gatekeeper
  api_key:
    secure: ThFrqAddjmmRkTvn1aLQzfiGErCfXZslUGAeScIdjTnoA21d7gb6qMQGAg3ewgr5u+p97ArenChDszFNGySsV+MpuChkkwYsFuMjqirp2F7zgLDHntvEwMnm4m4sKucka8CONa+cUMOnm3Z6kmcaGTomWTGg/JuFLPqqHpMAmNk=
