language: ruby
# We don't specify a list of ruby versions, as Travis will fall back to .ruby-version
dist: xenial
bundler_args: "--without deployment"
sudo: required
node_js:
- '10'
cache:
  bundler: true
script:
  - "bundle exec rubocop"
  - "bundle exec rake"
