---
:searches:
  Find assets by barcode: e7d2fec0-956f-11e3-8255-44fb42fffecc
  Find user by swipecard code: e7e52730-956f-11e3-8255-44fb42fffecc
  Find lot by lot number: 689a48a0-9d46-11e3-8fed-44fb42fffecc
  Find robot by barcode: 689a48a0-9d46-11e3-8fed-44fb42fffedd
  Find qcable by barcode: 689a48a0-9d46-11e3-8fed-44fb42fffeff
:printers:
  96 Well Plate:
  - :name: plate_example
    :uuid: baac0dea-0000-0000-0000-000000000000
  1D Tube:
  - :name: tube_example
    :uuid: baac0dea-0000-0000-0000-000000000001
  384 Well Plate:
  - :name: tef_plate_example
    :uuid: baac0dea-0000-0000-0000-000000000002
:templates:
  :plate_template:
  - :name: Example Plate Layout
    :uuid: 2f750200-9570-11e3-8f17-44fb42fffecc
  :tag_layout_template:
  - :name: Example Tag Template
    :uuid: ecd5cd30-956f-11e3-8255-44fb42fffecc
  - :name: Another Tag Layout
    :uuid: ecd7a1f0-956f-11e3-8255-44fb42fffecc
:lot_types:
  IDT Tags:
    :uuid: ee0b18e0-956f-11e3-8255-44fb42fffecc
    :template_class: TagLayoutTemplate
  IDT Reporters:
    :uuid: ee135640-956f-11e3-8255-44fb42fffecc
    :template_class: PlateTemplate
